# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kalo < Formula
  desc "Kalo CLI - Plugin-based code generation and database management"
  homepage "https://github.com/kalo-build/kalo-cli"
  version "0.0.1-dev-300126"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.1-dev-300126/kalo_0.0.1-dev-300126_darwin_x86_64.tar.gz"
      sha256 "9cd4c284ce5ef037e06a23cdbe20337f13dd1673b6f911de38dc99d49eff5ac7"

      def install
        bin.install "kalo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.1-dev-300126/kalo_0.0.1-dev-300126_darwin_arm64.tar.gz"
      sha256 "6d6de4c77fc11d3bf48bcffd08f639ff4ee2b654a774ad267cbfa311a48ae029"

      def install
        bin.install "kalo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.1-dev-300126/kalo_0.0.1-dev-300126_linux_x86_64.tar.gz"
      sha256 "bea66775b3617f52ab255cc6d8254be2ba3080397226a0914cf899a9eb60b464"
      def install
        bin.install "kalo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.1-dev-300126/kalo_0.0.1-dev-300126_linux_arm64.tar.gz"
      sha256 "9047a41a704e97e6d45b6cd9ae0f062a09bf9963185774d67c5f955fe1ccf2f0"
      def install
        bin.install "kalo"
      end
    end
  end

  test do
    system "#{bin}/kalo", "--version"
  end
end
