# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kalo < Formula
  desc "Kalo CLI - Plugin-based code generation and database management"
  homepage "https://github.com/kalo-build/kalo-cli"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.4/kalo_0.0.4_darwin_x86_64.tar.gz"
      sha256 "f3b0dcb5a6591a334742d8515c2784f2aad8461a4da30b234179de1c3eee07e0"

      def install
        bin.install "kalo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.4/kalo_0.0.4_darwin_arm64.tar.gz"
      sha256 "b65de610d2fff3a551b204ebfa68992798fee20d2c5caa17c12822be2bfef7cd"

      def install
        bin.install "kalo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.4/kalo_0.0.4_linux_x86_64.tar.gz"
      sha256 "d42d61d557b598320b867e4c6505edad60eb6842f77a4d009e0a64f3d693eb4e"
      def install
        bin.install "kalo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.4/kalo_0.0.4_linux_arm64.tar.gz"
      sha256 "b040c1d44307f88fe547887b5c2ed81aace7684826b789d74e86566e905d7c3c"
      def install
        bin.install "kalo"
      end
    end
  end

  test do
    system "#{bin}/kalo", "--version"
  end
end
