# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kalo < Formula
  desc "Kalo CLI - Plugin-based code generation and database management"
  homepage "https://github.com/kalo-build/kalo-cli"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.3/kalo_0.0.3_darwin_x86_64.tar.gz"
      sha256 "68f45d375c2196f1536baf50916ebd5f5c5e1129c7bf584cc7fe82a9816da9e5"

      def install
        bin.install "kalo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.3/kalo_0.0.3_darwin_arm64.tar.gz"
      sha256 "ce515942ac7a604410452d660343b8e14a244749e550a7ced3f81d4961b17831"

      def install
        bin.install "kalo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.3/kalo_0.0.3_linux_x86_64.tar.gz"
      sha256 "ce8e5f78d1aeb3a4f95df098a064c660789e191be71d6617fa5fe3727c1c1998"
      def install
        bin.install "kalo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kalo-build/kalo-cli/releases/download/v0.0.3/kalo_0.0.3_linux_arm64.tar.gz"
      sha256 "eb475e637c1df04d3d1db7aa39745225ccb1f5ca9e8d670ed06191f966dff5c3"
      def install
        bin.install "kalo"
      end
    end
  end

  test do
    system "#{bin}/kalo", "--version"
  end
end
